---
title: "Introduction to Rmarkdown Exercise"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This repository holds materials for the first course assignment.
We simply want you to introduce yourselves and your research interests to us,
while at the same time learning how to write things using Rmarkdown.

The file `about-me.Rmd` provides a skeleton to follow.  You should just
edit that file, modifying it to include you own information in it.  There are certain goals
in each section (like using numbered lists, or writing code in fenced code blocks) as listed
in each section.  

The file `about-me-example.Rmd` shows an example of what your response should look like.
You can study it to learn about Rmarkdown syntax.

You might try knitting your Rmd to other formats: (HTML, PDF, Word).  Note that
to get the PDF version done right, you probably have to add an image which is
your original JPG, but converted to a PDF.  (i.e. like `images/eric.pdf`).

Once you are done. Commit all the changes and any new files, and push those back to GitHub.
That constitutes turning the assignment in.




